# Uncomment the next line to define a global platform for your project
# platform :ios, '11.0'

target 'WeM0vies' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WeM0vies
 pod 'Kingfisher', '~> 7.0'
end
